#!/usr/bin/env python3

import sys, os, time
import requests
import urllib3
from dotenv import load_dotenv
import argparse
import paho.mqtt.client as MQTT_Client

load_dotenv()

cli = argparse.ArgumentParser( description='Watch MVI Edge Alerts' )

cli.add_argument('--host', help = 'Hostname', default = os.getenv('MVIE_HOST') )
cli.add_argument('--cert', help = 'CA Cert File', default = os.getenv('MVIE_CERT') )
cli.add_argument('--device', help = 'Input Device Name', default = os.getenv('MVIE_DEVICE') )

cli.add_argument('--mqtt-port', help = 'MQTT Port', type=int, default = os.getenv('MQTT_PORT') )
cli.add_argument('--mqtt-sub-topic', help = 'MQTT (Gateway) Topic', default = os.getenv('MQTT_SUB_TOPIC') )

args = cli.parse_args()

def on_connect(client, userdata, flags, rc):
    print("MQTT Connected")

mqtt = MQTT_Client.Client()

mqtt.on_connect = on_connect

mqtt.tls_set(args.cert)
mqtt.tls_insecure_set(True)
mqtt.connect(args.host, args.mqtt_port, 60)
mqtt.loop_start()

time.sleep(1)

while (True):

    id = input("Serial # / ID: ")

    if not len(id):
        id = str(time.time())

    # publish the barcode
    mqtt.publish(args.mqtt_sub_topic, id)
    